/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b423daac-d7ff-4cf2-8b3b-acee35cc0c51",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_gPbzbv6AV",
    "aws_user_pools_web_client_id": "6uqs22kbkn1e25mhbumnt46pv9",
    "oauth": {}
};


export default awsmobile;
